### ISSUE TITLE
[Bug]: Templates with values require default value to be specified in the template declaration in order to use the template variable as a decorator value

### ISSUE THREAD

**Issue by dmytrol** [microsoft/typespec#4399]
### Describe the bug

Consider the following code:

```
import "@typespec/http";

using TypeSpec.Http;

model GenericListOKResponse<T, L extends valueof integer> {
    ...OkResponse;
    @header contentType: "application/json";

    @bodyRoot
    body: {
        @maxItems(L)
        items: T[],

        @minValue(0)
        @maxValue(2147483647)
        @example(100)
        total: int32
    }
}
```

As described in the "Reproduction" section, this code won't compile in TypeSpec 0.58.1

Now, change the model declaration as follows:

`model GenericListOKResponse<T, L extends valueof integer = 100> {`

and voila! - the compilation error is gone for good.

I'd think the compiler should be able to infer the type of `L` from the `extends valueof integer` declaration but for some reason the compiler fails to perform the type inference properly without the default value "hint".

### Reproduction

Install 

```
"@typespec/compiler": "0.58.1",
"@typespec/http": "0.58.0",
```

Create a new TypeSpec file and define a model like this:

```
import "@typespec/http";

using TypeSpec.Http;

model GenericListOKResponse<T, L extends valueof integer> {
    ...OkResponse;
    @header contentType: "application/json";

    @bodyRoot
    body: {
        @maxItems(L)
        items: T[],

        @minValue(0)
        @maxValue(2147483647)
        @example(100)
        total: int32
    }
}
```

Compile the code. The compiler will report an error 

> error invalid-argument: Argument of type 'unknown' is not assignable to parameter of type 'valueof integer'
> @maxItems(L)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
This works fine for me in the [playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKbW9kZWwgR2VuZXJpY0xpc3RPS1Jlc3BvbnNlPFQsIEwgZXh0ZW5kcyB2YWx1ZW9mIGludGVnZXI%2BIHsKICAuLi5Pa8gwOwogIEBoZWFkZXIgY29udGVudMRuOiAiYXBwbGljYXRpb24vanNvbuQAjyAgQGJvZHlSb290CiAgxAs6xVMgIEBtYXhJdGVtcyhMKcURacQNOiBUW13FOMQiaW5W5ACQKDDGIsQzxhEyMTQ3NDgzNjQ3xxpleGFtcGxlKDEwxyx0b3RhbDrkAMgzMuQAs307Cn0K6AEJTXlSZXMgaXP3ARJzdHJpbmcsIDIwMD47&e=%40typespec%2Fopenapi3&options=%7B%7D) 

are you able to share a repro there?
